services:
  five_cards_backend:
    build:
      context: ./backend
      target: development
    restart: unless-stopped
    env_file: ./backend/.env
    container_name: 5cards-backend
    volumes: 
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - five_cards_db
    command: sh -c "npx drizzle-kit migrate && npx drizzle-kit push && npm run dev"
    networks:
      - five_cards_network

  five_cards_frontend:
    build:
      context: ./frontend
      target: development
    restart: unless-stopped
    env_file: ./frontend/.env
    container_name: 5cards-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - five_cards_backend
    networks:
      - five_cards_network

  five_cards_db:
    image: postgres:16
    container_name: 5cards-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=five_cards
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - five_cards_network

volumes:
  postgres_data:
networks:
  five_cards_network:
    external: true
      
