services:
  five_cards_backend:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    env_file: ./backend/.env
    container_name: 5cards-backend
    command: sh -c "npx drizzle-kit migrate && npx drizzle-kit push && node dist/index.js"
    depends_on:
      - five_cards_db
    networks:
      - five_cards_network

  five_cards_frontend:
    build:
      context: ./frontend
      target: production
    restart: unless-stopped
    container_name: 5cards-frontend
    depends_on:
      - five_cards_backend
    networks:
      - five_cards_network

  five_cards_db:
    image: postgres:16
    container_name: 5cards-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=five_cards
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - five_cards_network


volumes:
  postgres_data:
networks:
  five_cards_network:
    external: true
      
